services:
  privacy-survey:
    build:
      context: .
      dockerfile: Dockerfile

    container_name: privacy-survey

    volumes:
      - .:/app
      - ../paper:/paper:ro

    working_dir: /app

    env_file:
      - .env

    stdin_open: true
    tty: true

    command: sleep infinity